### ISSUE TITLE
Cannot run on Rpi2

### ISSUE THREAD

**Issue by FishTest** [Gadgetoid/WiringPi2-Python#25]
pi@raspberrypi ~/Adafruit_Python_SSD1306/examples $ sudo python animate.py
Traceback (most recent call last):
  File "animate.py", line 47, in <module>
    disp = Adafruit_SSD1306.SSD1306_128_32(rst=RST)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306-1.5.0-py2.7.egg/Adafruit_SSD1306/SSD1306.py", line 284, in __init__
    gpio, spi, i2c_bus, i2c_address, i2c)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306-1.5.0-py2.7.egg/Adafruit_SSD1306/SSD1306.py", line 84, in __init__
    self._gpio = GPIO.get_platform_gpio()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO-0.8.0-py2.7.egg/Adafruit_GPIO/GPIO.py", line 318, in get_platform_gpio
    import RPi.GPIO
RuntimeError: This module can only be run on a Raspberry Pi!

**Comment by Gadgetoid** [comment]
"import RPi.GPIO"

WiringPi isn't RPi.GPIO they're totally different libraries.

Fortunately, I still know the solution...

You need to update your RPi.GPIO library, try:

    sudo apt-get update
    sudo apt-get upgrade
